"""Framework-wide shared infrastructure — types, errors, and markers."""

from canary_framework.common.config import CanaryConfig
from canary_framework.common.errors import (
    ApplicationNotInitializedError,
    CanaryFrameworkError,
    CircularDependencyError,
    ConfigurationError,
    DependencyDirectionError,
    DependencyInjectionError,
    LifecycleHookError,
    LifecycleStateError,
    RouteCompilationError,
    ServiceNotFoundError,
)
from canary_framework.common.routing import ASGIApp, ResponseSpec, RouteContext, RouteSpec
from canary_framework.common.types import (
    CF_NAME_ATTR,
    CF_SERVICE_MARKER,
    CF_SERVICE_META,
    LifecycleState,
    ModuleMeta,
    RouterMeta,
    ServiceEntry,
    ServiceMeta,
    get_module_meta,
    get_router_meta,
    get_service_meta,
    is_cf_module,
    is_cf_router,
    is_cf_service,
    unwrap_optional,
)

__all__ = [
    "CF_NAME_ATTR",
    "CF_SERVICE_MARKER",
    "CF_SERVICE_META",
    "ASGIApp",
    "ApplicationNotInitializedError",
    "CanaryConfig",
    "CanaryFrameworkError",
    "CircularDependencyError",
    "ConfigurationError",
    "DependencyDirectionError",
    "DependencyInjectionError",
    "LifecycleHookError",
    "LifecycleState",
    "LifecycleStateError",
    "ModuleMeta",
    "ResponseSpec",
    "RouteCompilationError",
    "RouteContext",
    "RouteSpec",
    "RouterMeta",
    "ServiceEntry",
    "ServiceMeta",
    "ServiceNotFoundError",
    "get_module_meta",
    "get_router_meta",
    "get_service_meta",
    "is_cf_module",
    "is_cf_router",
    "is_cf_service",
    "unwrap_optional",
]
